# Pandas Series

In [1]:
import pandas as pd
import numpy as np

## Creation of Pandas Series

### Series() function

In [6]:
pd.Series(data = [10,88,3,4,5]) #Data ilk parametre. 
                                # data : array-like, Iterable, dict, or scalar value Contains data stored in Series.
                                #pandas serisinin indexi vardır. 

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [2]:
ser = pd.Series([10,88,3,4,5])
ser

0    10
1    88
2     3
3     4
4     5
dtype: int64

## Pd serileri liste, array ve dictionary alabilir.  Dict: key: indeks olur, valueler seri. 

In [13]:
my_data = [10,20,30]
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [14]:
d = {"a":10, "b": 20, "c": 30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [15]:
arr = np.array(my_data)
pd.Series(data = arr)

0    10
1    20
2    30
dtype: int32

In [17]:
print(type(ser))
print(ser.dtype)
print(ser.size)
print(ser.ndim) #ndim attribute, parantezsiz kullanıldı
print(ser.values)
print(ser.head(3))#head methodu, parantezle kullanıldı

<class 'pandas.core.series.Series'>
int64
5
1
[10 88  3  4  5]
0    10
1    88
2     3
dtype: int64


In [10]:
for i in ser.values:
    print(i)

10
88
3
4
5


In [14]:
[i for i in ser.values]

[10, 88, 3, 4, 5]

In [19]:
string="clarusway"
[i for i in string]

['c', 'l', 'a', 'r', 'u', 's', 'w', 'a', 'y']

In [20]:
pd.Series([i for i in string])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

# creating ps by using list, numpy array or dict

In [24]:
label = ["a", "b", "c"]
my_list=[10,20,30]
arr = np.array([10,20,30])
d = {"a":10, "b":20, "c":30}

In [25]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [27]:
pd.Series(data=my_list, index = label)

a    10
b    20
c    30
dtype: int64

In [28]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [29]:
pd.Series(arr, label)

a    10
b    20
c    30
dtype: int32

In [30]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [31]:
pd.Series(data=label)

0    a
1    b
2    c
dtype: object

In [33]:
pd.Series([sum, print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [34]:
mix_data = [1, "cat", True]

In [35]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

# pandas serileri metodları: .sort_index, .sort_value, .isin

# sort index

In [36]:
s = pd.Series(["p", "q", "r", "s"], index = [3,2,4,5])

In [39]:
s.sort_index()

2    q
3    p
4    r
5    s
dtype: object

In [40]:
s.sort_index(ascending=False)

5    s
4    r
3    p
2    q
dtype: object

In [41]:
s#değişmemiş 

3    p
2    q
4    r
5    s
dtype: object

# sort inplace: kalıcı olarak değiştirir

In [42]:
s.sort_index(inplace=True)

In [43]:
s

2    q
3    p
4    r
5    s
dtype: object

In [44]:
s

2    q
3    p
4    r
5    s
dtype: object

# np.nan

In [ ]:
# by default NaNs are put at the end, but use na_positon to place them at the beginning. nan değeri yok demek

In [46]:
s = pd.Series(["p", "q", "r", "s"], index = [3,2,4,np.nan])
s.sort_index(na_position="first")

NaN    s
2.0    q
3.0    p
4.0    r
dtype: object

# sort_values

In [50]:
s = pd.Series([np.nan, 2,4, 10,7])
s

0     NaN
1     2.0
2     4.0
3    10.0
4     7.0
dtype: float64

In [55]:
s.sort_values(ascending =True)

1     2.0
2     4.0
4     7.0
3    10.0
0     NaN
dtype: float64

In [47]:
s = pd.Series(["t", "q", "s", "p", "r"])
s

0    t
1    q
2    s
3    p
4    r
dtype: object

In [48]:
s.sort_values()

3    p
1    q
4    r
2    s
0    t
dtype: object

In [2]:
import numpy as np

In [3]:
import pandas as pd

# isin

In [5]:
s = pd.Series(["dog", "cow", "dog", "cat", "dog", "lion"], name="animal")

In [8]:
s.isin(["cow", "dog"])#iterable olarak atananları araştırır booleana döndürür. bunlardan biri varsa true döner

0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

In [7]:
s.isin(["dog"])

0     True
1    False
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

# indexing pandas series

In [9]:
ser1 = pd.Series([1,2,3,4], index = ["USA", "Germany", "USSR", "Japan"])

In [10]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [11]:
ser2 = pd.Series([1,2,3,4], index = ["USA", "Germany", "Italy", "Japan"])

In [12]:
ser2

USA        1
Germany    2
Italy      3
Japan      4
dtype: int64

In [13]:
ser1["USA"]

1

In [16]:
labels = ["a", "b", "c"]
my_list=[10,20,30]
arr = np.array([10,20,30])
d = {"a":10, "b":20, "c":30}

In [17]:
ser3 = pd.Series(data=labels)

In [18]:
ser3

0    a
1    b
2    c
dtype: object

In [19]:
ser3[0]

'a'

In [20]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [22]:
a = np.array([1,2,33,444,75])

In [23]:
a

array([  1,   2,  33, 444,  75])

In [24]:
panser=pd.Series(a)

In [25]:
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [26]:
panser[0]

1

In [27]:
panser[0:3]

0     1
1     2
2    33
dtype: int32

In [28]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [29]:
ser1["USA":"USSR"]

USA        1
Germany    2
USSR       3
dtype: int64

In [30]:
panser = pd.Series([121,200,150,99], index=("ali", "veli", "gul", "nur"))

In [31]:
panser

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [32]:
panser["ali"]

121

In [33]:
panser[0]

121

In [34]:
panser[["veli", "nur"]]

veli    200
nur      99
dtype: int64

In [35]:
panser[0:3]

ali     121
veli    200
gul     150
dtype: int64

In [36]:
panser["ali":"nur"]

ali     121
veli    200
gul     150
nur      99
dtype: int64

In [37]:
panser.index

Index(['ali', 'veli', 'gul', 'nur'], dtype='object')

In [38]:
panser.values

array([121, 200, 150,  99], dtype=int64)

In [39]:
panser.items

<bound method Series.items of ali     121
veli    200
gul     150
nur      99
dtype: int64>

In [40]:
panser.items()

In [42]:
list(panser.items())

[('ali', 121), ('veli', 200), ('gul', 150), ('nur', 99)]

In [43]:
for index, value in panser.items():
    print(index, "-", value)

ali - 121
veli - 200
gul - 150
nur - 99


In [44]:
"mehmet" in panser

False

In [45]:
"ali" in panser

True

In [47]:
99 in panser.values

True

In [49]:
panser["veli"]

200

In [50]:
panser["veli"]=571

In [51]:
panser

ali     121
veli    571
gul     150
nur      99
dtype: int64

In [52]:
panser>130

ali     False
veli     True
gul      True
nur     False
dtype: bool

In [53]:
panser[panser>130]

veli    571
gul     150
dtype: int64

In [3]:
labels = ["a", "b", "c"]
my_data=[10,20,30]
arr = np.array(my_data)
d = {"a":10, "b":20, "c":30}

In [4]:
pd.Series(data=my_data)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(my_data, labels)

a    10
b    20
c    30
dtype: int64

In [7]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [8]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [9]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [10]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [11]:
pd.Series(data=sum)

0    <built-in function sum>
dtype: object

In [12]:
ser1=pd.Series([1,2,3,4], ["USA", "Germany", "USSR", "Japan"])

In [13]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [14]:
ser2=pd.Series([1,2,5,4], ["USA", "Germany", "Italy", "Japan"])

In [15]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [16]:
ser1["USA"]

1

In [17]:
ser3=pd.Series(data=labels)

In [18]:
ser3

0    a
1    b
2    c
dtype: object

In [19]:
ser3[0]

'a'

In [20]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

## len() function

In [10]:
len(arr)

3

## unique() method

In [2]:
pd.Series([2,1,3,3,])

0    2
1    1
2    3
3    3
dtype: int64

In [3]:
pd.unique(pd.Series([2,1,3,3,]))

array([2, 1, 3], dtype=int64)

In [4]:
type(pd.Series([2,1,3,3,]))

pandas.core.series.Series

In [5]:
type(pd.unique(pd.Series([2,1,3,3,])))

numpy.ndarray

In [8]:
pd.Series([2] + [1] *5)

0    2
1    1
2    1
3    1
4    1
5    1
dtype: int64

In [9]:
pd.unique(pd.Series([2] + [1] *5))

array([2, 1], dtype=int64)

### astype() method

In [11]:
ser = pd.Series([1,2], dtype = "int32")
ser

0    1
1    2
dtype: int32

In [12]:
ser.astype("int64")

0    1
1    2
dtype: int64

In [14]:
ser.astype("category") # Convert to categorical dtype 

0    1
1    2
dtype: category
Categories (2, int64): [1, 2]

In [15]:
cat_dtype = pd.api.types.CategoricalDtype(categories=[2, 1], ordered=True)# Convert to ordered categorical type with custom ordering:

In [16]:
ser.astype(cat_dtype)

0    1
1    2
dtype: category
Categories (2, int64): [2 < 1]

In [17]:
s1 = pd.Series([1, 2])
s2 = s1.astype('int64', copy=False) # Note that using copy=False and changing data on a new pandas object may propagate changes:

In [18]:
s2[0] = 10
s1  # note that s1[0] has changed too

0    10
1     2
dtype: int64

## cat() method

`Docstring`: Concatenate strings in the Series/Index with given separator.

In [4]:
s = pd.Series(["a", "b", np.nan, "d"])
s

0      a
1      b
2    NaN
3      d
dtype: object

In [3]:
s.str.cat(sep = " ")

'a b d'

In [5]:
s.str.cat(sep = "/", na_rep="?")

'a/b/?/d'

In [6]:
s.str.cat(['A', 'B', 'C', 'D'], sep=',', na_rep='-')
#If `others` is specified, corresponding values are concatenated with the separator. Result will be a Series of strings.

0    a,A
1    b,B
2    -,C
3    d,D
dtype: object

## replace method()

In [29]:
s = pd.Series(range(5))
#s = pd.Series([0, 1, 2, 3, 4])
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [30]:
s.replace(0,555)

0    555
1      1
2      2
3      3
4      4
dtype: int64

In [31]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [32]:
s.replace([1, 2], method='bfill')

0    0
1    3
2    3
3    3
4    4
dtype: int64