In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.DataFrame({"col1": [1,2,3,4],
                "col2": [444,555,666,444],
                "col3": ["abc", "def", "ghi", "xyz"]})

In [4]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

# Finding unique values

In [5]:
df["col2"].unique()

array([444, 555, 666], dtype=int64)

# Finding number of unique values

In [6]:
len(df["col2"].unique())

3

In [7]:
df["col2"].nunique()

3

# exercises

In [8]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [1, 1, 1]})

In [9]:
df

A  B
0  1  1
1  2  1
2  3  1

In [10]:
df.nunique()

A    3
B    1
dtype: int64

In [11]:
df.nunique(axis=1)

0    1
1    2
2    2
dtype: int64

In [12]:
df["B"].nunique()

1

In [13]:
pd.Series([2,1,3,3])

0    2
1    1
2    3
3    3
dtype: int64

In [16]:
pd.unique(pd.Series([2,1,3,3]))

array([2, 1, 3], dtype=int64)

In [17]:
type(pd.unique(pd.Series([2,1,3,3])))

numpy.ndarray

In [19]:
pd.unique(pd.Series([2] + [1] * 5))

array([2, 1], dtype=int64)

In [20]:
pd.Series([2] + [1] * 5)


0    2
1    1
2    1
3    1
4    1
5    1
dtype: int64

In [21]:
pd.unique(list('baabc'))


array(['b', 'a', 'c'], dtype=object)