In [1]:
import numpy as np

In [2]:
revenue = np.array([[180, 200, 220], [24,36,40], [12,18,20]])
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [3]:
expenses = np.array([[80,90,100], [10,16,20], [8,10,10]])
expenses

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [4]:
profit = revenue-expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [5]:
sales = np.array([[30, 40, 50], [5,10,15], [2,5,7]])
sales

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [6]:
price = np.array([1000, 400, 1200])
price

array([1000,  400, 1200])

In [7]:
total_sales = price*sales

In [8]:
total_sales #broadcasting

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [9]:
np.dot(price, sales)

array([34400, 50000, 64400])

In [10]:
revenueD = np.array([[200, 220, 250], [68,79,105], [110, 140, 180], [80,85,90]])

In [11]:
revenueD

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [12]:
exchange_rate = 20

In [13]:
revenueT= exchange_rate*revenueD

In [14]:
revenueT

array([[4000, 4400, 5000],
       [1360, 1580, 2100],
       [2200, 2800, 3600],
       [1600, 1700, 1800]])

In [15]:
import pandas as pd
pd.DataFrame(data= revenueT, index = ["Reliance", "Infosys", "TCS", "Wipro"],
             columns = ["FY2018","FY2019","FY2020" ])

FY2018  FY2019  FY2020
Reliance    4000    4400    5000
Infosys     1360    1580    2100
TCS         2200    2800    3600
Wipro       1600    1700    1800

In [16]:
A = np.array([[1,2], [3,4], [5,6]])

In [17]:
A # 3*2 matrice

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
B = np.array([[1,2,3], [4,5,6]])

In [19]:
B # 2*3 matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.dot(A,B)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [21]:
C = np.array([[1,2], [3,4]])

In [22]:
C

array([[1, 2],
       [3, 4]])

In [23]:
np.dot(A,C)

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [24]:
D = np.array([[1,2,3], [4,5,6], [7,8,9]])
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
np.dot(B,D)

array([[30, 36, 42],
       [66, 81, 96]])