<h2 style="color:green" align="center">Implement Gradient Descent For Neural Network (or Logistic Regression)</h2>

<h4 style="color:blue">Predicting if a person would buy life insurnace based on his age using logistic regression</h4>

Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't).

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("insurance_data.csv")

In [4]:
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

**Split train and test set**

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df[["age", "affordibility"]]
y = df.bought_insurance

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 25)

In [10]:
X_train.head()

age  affordibility
0    22              1
13   29              0
6    55              0
17   58              1
24   50              1

In [11]:
len(X_train)

22

**Preprocessing: Scale the data so that both age and affordibility are in same scaling range**

In [14]:
#scaling: bring age and affordibility to the same scale
X_train_scaled = X_train.copy()
X_train_scaled["age"] = X_train_scaled["age"]/100

In [15]:
X_test_scaled = X_test.copy()
X_test_scaled["age"] = X_test_scaled["age"]/100

**Model Building: First build a model in keras/tensorflow and see what weights and bias values it comes up with. We will than try to reproduce same weights and bias in our plain python implementation of gradient descent. Below is the architecture of our simple neural network**

<img src = "nn.png" height=800 width=800/>

In [12]:
import keras

In [36]:
model = keras.Sequential([
    keras.layers.Dense(1, # with only one layer, neuron
                       input_shape = (2,), # age and affordibility are 2 params in the input
                       activation = "sigmoid",
                       kernel_initializer="ones", #weights starts with 1
                       bias_initializer = "zeros" # bias starts with 0
                       )
                          ])


model.compile(optimizer="adam",
              loss = "binary_crossentropy",
              metrics = ["accuracy"]
              )

model.fit(                          # model fit runs the training.
          X_train_scaled, y_train,
          epochs = 500 # tra,l and error: initialy 1000 and up, 5000 gives the best accuracy
          )

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 0.7113 - accuracy: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7110 - accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 16ms/step - loss: 0.7106 - accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 16ms/step - loss: 0.7102 - accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 19ms/step - loss: 0.7098 - accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 17ms/step - loss: 0.7094 - accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 21ms/step - loss: 0.7091 - accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 12ms/step - loss: 0.7087 - accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 17ms/step - loss: 0.7083 - accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 13ms/step - loss: 0.7079 - accuracy: 0.5000
Epoch 11/500
1/1 [====

1/1 [==============================] - 0s 13ms/step - loss: 0.6835 - accuracy: 0.5000
Epoch 84/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6832 - accuracy: 0.5000
Epoch 85/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6829 - accuracy: 0.5000
Epoch 86/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6826 - accuracy: 0.5000
Epoch 87/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6823 - accuracy: 0.5000
Epoch 88/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6820 - accuracy: 0.5000
Epoch 89/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6817 - accuracy: 0.5000
Epoch 90/500
1/1 [==============================] - 0s 12ms/step - loss: 0.6814 - accuracy: 0.5000
Epoch 91/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6811 - accuracy: 0.5000
Epoch 92/500
1/1 [==============================] - 0s 11ms/step - loss: 0.6808 - accuracy: 0.5000
Epoch 93/500
1/1 [=====

1/1 [==============================] - 0s 20ms/step - loss: 0.6626 - accuracy: 0.5000
Epoch 166/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6624 - accuracy: 0.5000
Epoch 167/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6622 - accuracy: 0.5000
Epoch 168/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6620 - accuracy: 0.5000
Epoch 169/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6617 - accuracy: 0.5000
Epoch 170/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6615 - accuracy: 0.5000
Epoch 171/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6613 - accuracy: 0.5000
Epoch 172/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6611 - accuracy: 0.5000
Epoch 173/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6609 - accuracy: 0.5455
Epoch 174/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6607 - accuracy: 0.5455
Epoch 175/500


1/1 [==============================] - 0s 16ms/step - loss: 0.6479 - accuracy: 0.5909
Epoch 248/500
1/1 [==============================] - 0s 20ms/step - loss: 0.6477 - accuracy: 0.5909
Epoch 249/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6476 - accuracy: 0.5909
Epoch 250/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6474 - accuracy: 0.5909
Epoch 251/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6473 - accuracy: 0.5909
Epoch 252/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6471 - accuracy: 0.5909
Epoch 253/500
1/1 [==============================] - 0s 19ms/step - loss: 0.6470 - accuracy: 0.5909
Epoch 254/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6468 - accuracy: 0.5909
Epoch 255/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6467 - accuracy: 0.5909
Epoch 256/500
1/1 [==============================] - 0s 19ms/step - loss: 0.6465 - accuracy: 0.5909
Epoch 257/500


1/1 [==============================] - 0s 24ms/step - loss: 0.6378 - accuracy: 0.6364
Epoch 330/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6377 - accuracy: 0.6364
Epoch 331/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6376 - accuracy: 0.6364
Epoch 332/500
1/1 [==============================] - 0s 14ms/step - loss: 0.6375 - accuracy: 0.6364
Epoch 333/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6374 - accuracy: 0.6364
Epoch 334/500
1/1 [==============================] - 0s 21ms/step - loss: 0.6373 - accuracy: 0.6364
Epoch 335/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6372 - accuracy: 0.6364
Epoch 336/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6371 - accuracy: 0.6364
Epoch 337/500
1/1 [==============================] - 0s 19ms/step - loss: 0.6370 - accuracy: 0.6364
Epoch 338/500
1/1 [==============================] - 0s 20ms/step - loss: 0.6369 - accuracy: 0.6364
Epoch 339/500


1/1 [==============================] - 0s 17ms/step - loss: 0.6309 - accuracy: 0.6364
Epoch 412/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6308 - accuracy: 0.6364
Epoch 413/500
1/1 [==============================] - 0s 14ms/step - loss: 0.6307 - accuracy: 0.6364
Epoch 414/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6307 - accuracy: 0.6364
Epoch 415/500
1/1 [==============================] - 0s 19ms/step - loss: 0.6306 - accuracy: 0.6364
Epoch 416/500
1/1 [==============================] - 0s 16ms/step - loss: 0.6305 - accuracy: 0.6364
Epoch 417/500
1/1 [==============================] - 0s 14ms/step - loss: 0.6305 - accuracy: 0.6364
Epoch 418/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6304 - accuracy: 0.6364
Epoch 419/500
1/1 [==============================] - 0s 23ms/step - loss: 0.6303 - accuracy: 0.6364
Epoch 420/500
1/1 [==============================] - 0s 18ms/step - loss: 0.6302 - accuracy: 0.6364
Epoch 421/500


1/1 [==============================] - 0s 14ms/step - loss: 0.6257 - accuracy: 0.6364
Epoch 494/500
1/1 [==============================] - 0s 10ms/step - loss: 0.6257 - accuracy: 0.6364
Epoch 495/500
1/1 [==============================] - 0s 15ms/step - loss: 0.6256 - accuracy: 0.6364
Epoch 496/500
1/1 [==============================] - 0s 14ms/step - loss: 0.6256 - accuracy: 0.6364
Epoch 497/500
1/1 [==============================] - 0s 17ms/step - loss: 0.6255 - accuracy: 0.6364
Epoch 498/500
1/1 [==============================] - 0s 21ms/step - loss: 0.6255 - accuracy: 0.6364
Epoch 499/500
1/1 [==============================] - 0s 19ms/step - loss: 0.6254 - accuracy: 0.6364
Epoch 500/500
1/1 [==============================] - 0s 13ms/step - loss: 0.6253 - accuracy: 0.6364


**Evaluate the model on test set**

In [37]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 1s 513ms/step - loss: 0.6210 - accuracy: 0.6667


[0.621041476726532, 0.6666666865348816]

In [38]:
model.predict(X_test_scaled)#anything that bigger than 0.5, it will buy the insurance

1/1 [==============================] - 0s 232ms/step


array([[0.66075516],
       [0.6084721 ],
       [0.45149705],
       [0.6268543 ],
       [0.66423655],
       [0.68474233]], dtype=float32)

In [39]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

**Now get the value of weights and bias from the model**

In [40]:
coef, intercept = model.get_weights()

In [41]:
coef, intercept

(array([[0.7785072 ],
        [0.69779867]], dtype=float32),
 array([-0.39703575], dtype=float32))

**This means w1=5.060867, w2=1.4086502, bias =-2.9137027**

In [22]:
#building network from scratch without tensorflow

In [42]:
import math
def sigmoid(x):
 return 1/ (1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [43]:
X_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

**Instead of model.predict, write our own prediction function that uses w1,w2 and bias**

In [44]:
#prediction function
def prediction_function(age, affordibility):
  weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
  return sigmoid(weighted_sum)

In [45]:
prediction_function(0.47,1)

0.6607551841052955

In [46]:
prediction_function(.18,1)

0.6084720839511557

**Now we start implementing gradient descent in plain python. Again the goal is to come up with same w1, w2 and bias that keras model calculated. We want to show how keras/tensorflow would have computed these values internally using gradient descent**

**First write couple of helper routines such as sigmoid and log_loss**

In [27]:
#implementing gradient descend function in python from scratch

In [47]:
# sigmoid vector function, takes vector, not one value
def sigmoid_numpy(X):
  return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [48]:
import numpy as np
def log_loss(y_test, y_predicted):
  epsilon = 1e-15
  y_predicted_new = [max(i, epsilon)for i in y_predicted]
  y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_test*np.log(y_predicted_new) + (1-y_test)*np.log(1-y_predicted_new))


**All right now comes the time to implement our final gradient descent function !! yay !!!**

In [49]:
#defining gradient descent function: helps to find weights, w1, w2, bias

def gradient_descent(age, affordibility, y_true, epochs, loss_threshold):
  w1 = w2= 1
  bias = 0
  rate = 0.5 # see if it runs fast
  n = len(age)

  for i in range(epochs):
    weighted_sum = w1 * age + w2 * affordibility + bias
    y_predicted = sigmoid_numpy(weighted_sum)

    loss = log_loss(y_true, y_predicted)

    # now operate the weights based on derivative function

    w1d = (1/2)*np.dot(np.transpose(age), (y_predicted - y_true))
    w2d = (1/2)*np.dot(np.transpose(affordibility), (y_predicted - y_true))

    bias_d = np.mean(y_predicted - y_true)

    w1 = w1 - rate * w1d
    w2 = w2 - rate * w2d
    bias = bias-rate *bias_d

    print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

    if loss <= loss_threshold:
      break
  return w1, w2, bias



In [50]:
gradient_descent(X_train_scaled["age"], X_train_scaled["affordibility"], y_train, 1000, 0.6252)

Epoch:0, w1:0.7239839681719467, w2:0.43182937933981824, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:1, w1:0.7176888289223157, w2:0.40213966848465077, bias:-0.16839255621822277, loss:0.6518225081030319
Epoch:2, w1:0.751465975355239, w2:0.44254926264698446, bias:-0.21440839079102986, loss:0.6463129923480861
Epoch:3, w1:0.7874064308489798, w2:0.4759505332461883, bias:-0.25953579121620785, loss:0.6416337302582155
Epoch:4, w1:0.8269369009086267, w2:0.5065812848761797, bias:-0.30346474682804275, loss:0.6371738314272632
Epoch:5, w1:0.8695247474349714, w2:0.5344999482421208, bias:-0.3463037469612078, loss:0.6329040678797876
Epoch:6, w1:0.9147988283414765, w2:0.5599883474117267, bias:-0.38812797722918135, loss:0.6288014701825863
Epoch:7, w1:0.9624182150220332, w2:0.5832885115236057, bias:-0.42900716239105463, loss:0.6248470912343181


(0.9624182150220332, 0.5832885115236057, -0.42900716239105463)

In [51]:
coef, intercept

(array([[0.7785072 ],
        [0.69779867]], dtype=float32),
 array([-0.39703575], dtype=float32))

**This shows that in the end we were able to come up with same value of w1,w2 and bias using a plain python implementation of gradient descent function**