<h2 style = "color:red" align = "center"> Keras Embedding Layer </h2>

In [ ]:
On the process of solving NLP task, it will compute embeddings on fly. 

Save embeddings on a file

In [36]:
import numpy as np

In [37]:
from tensorflow.keras.preprocessing.text import one_hot

In [38]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [39]:
from tensorflow.keras.models import Sequential

In [40]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [41]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [68]:
one_hot("amazing restaurant", 50)
# 30: vocabulary size

[2, 43]

**1.Converting reviews into one-hot encoding**

In [83]:
vocab_size = 50 #we initialize vocab size as 30

In [84]:
encoded_reviews = [one_hot(i, vocab_size) for i in reviews]

In [85]:
encoded_reviews

[[1, 6],
 [2, 43],
 [14, 14],
 [16, 36, 45],
 [4, 14, 21],
 [32, 6],
 [13, 14, 35],
 [42, 12],
 [42, 10],
 [2, 36]]

**2.Padding to fix length**

In [86]:
#we will make every vector size equal
#pad_sequence method

In [87]:
max_length= 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding = "post")
padded_reviews

array([[ 1,  6,  0],
       [ 2, 43,  0],
       [14, 14,  0],
       [16, 36, 45],
       [ 4, 14, 21],
       [32,  6,  0],
       [13, 14, 35],
       [42, 12,  0],
       [42, 10,  0],
       [ 2, 36,  0]])

**Embedded vector size**

In [88]:
#It is the feature number. 

In [89]:
embedded_vector_size=4

model = Sequential()

#1st layer is embedding layer-one-hot encoded matrix
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name = "embedding"))

#2nd layer: Flattened version of embedded vectors-product of embedding layer-random weighted and one-hot encoded vector of word
model.add(Flatten())

#3th layer is one nueron of sigmoid AF function. 
model.add(Dense(1,activation = "sigmoid"))

In [90]:
X = padded_reviews
y = sentiment

In [91]:
model.compile(optimizer = "adam", loss="binary_crossentropy", metrics= ["accuracy"])
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_6 (Flatten)         (None, 12)                0         
                                                                 
 dense_6 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213 (852.00 Byte)
Trainable params: 213 (852.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


**Training**

In [92]:
model.fit(X, y, epochs = 50, verbose=0)

**Evaluate the model**

In [93]:
loss, accuracy = model.evaluate(X,y)

1/1 [==============================] - 0s 317ms/step - loss: 0.6527 - accuracy: 1.0000


In [94]:
#Sentiment analysis is a fake problem. I am more interested with word embeddings. 
#Word embeddings are nothing but parameters in NN.

In [95]:
weights = model.get_layer("embedding").get_weights()[0]
len(weights)

50

In [96]:
#word embeddings for 
#nice:1,
#amazing: 2
#food:6 (initial one hot encoded numbers)
#embeddigns for nice and amazing should be the same: but dataset is very small: in big data vectors will be similar

In [97]:
weights[1]

array([ 0.09992317, -0.06860979,  0.03517278, -0.07445153], dtype=float32)

In [98]:
weights[2]

array([-0.00442587, -0.01750188, -0.05010382, -0.01046225], dtype=float32)