## Text Representation 

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv("C:/Users/Owner/nlp-tutorials/9_bag_of_words/spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [10]:
df.Category.value_counts() #inbalanced dataset.

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
my_dict = {"ham":0, "spam":1}

In [17]:
#df["Category"] = df["Category"].map(my_dict)
df["spam"] = df["Category"].apply(lambda x: 1 if x =="spam" else 0)

In [18]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X= df["Message"]
y= df["spam"]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2)

In [22]:
X_train.shape

(4457,)

In [24]:
X_test.shape

(1115,)

In [25]:
X_train[:4]

3092    LORD OF THE RINGS:RETURN OF THE KING in store ...
2803    And smile for me right now as you go and the w...
1146    Thank you, winner notified by sms. Good Luck! ...
3259    He fucking chickened out. He messaged me he wo...
Name: Message, dtype: object

### building Bag of Words model for numeric representation

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
v = CountVectorizer()

In [29]:
type(X_train.values)

numpy.ndarray

In [32]:
X_train_cv = v.fit_transform(X_train.values) #it will generate bow model for X_train
                            # fit_transform expects numpy array as argument, thats why we use X_train.values
X_train_cv 

<4457x7766 sparse matrix of type '<class 'numpy.int64'>'
	with 59851 stored elements in Compressed Sparse Row format>

In [33]:
# change sparse matrix into numpy array

In [47]:
X_train_np = X_train_cv.toarray()

In [37]:
X_train_cv.shape # 7766 unique word

(4457, 7766)

In [42]:
v.get_feature_names()[1000:1010]
#v.get_feature_names_out()

['apart',
 'apartment',
 'apes',
 'apeshit',
 'aphex',
 'apnt',
 'apo',
 'apologetic',
 'apologise',
 'apologize']

In [43]:
dir(v)#see methods

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_sort_features',
 '_stop_words_id',
 '_validate_custom_analyzer',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',
 'fixed_vocabulary_',
 'get_feature_names',
 'get_params',
 'get_stop_words'

In [ ]:
v.vocabulary_

In [48]:
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
X_train_np[:4][0]#first email

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [51]:
import numpy as np
np.where(X_train_np[0] !=0)

(array([1579, 1686, 1710, 2581, 3643, 3871, 3946, 4209, 4217, 4840, 4895,
        5722, 5767, 5795, 6340, 6462, 6495, 6504, 6815, 6936, 7112, 7538],
       dtype=int64),)

In [52]:
X_train[:4]

3092    LORD OF THE RINGS:RETURN OF THE KING in store ...
2803    And smile for me right now as you go and the w...
1146    Thank you, winner notified by sms. Good Luck! ...
3259    He fucking chickened out. He messaged me he wo...
Name: Message, dtype: object

In [53]:
X_train[:4][3092]

'LORD OF THE RINGS:RETURN OF THE KING in store NOW!REPLY LOTR by 2 June 4 Chance 2 WIN LOTR soundtrack CDs StdTxtRate. Reply STOP to end txts'

In [55]:
X_train_np[0][1579]

1

In [56]:
v.get_feature_names()[1579]

'by'

### building ML model

In [57]:
from sklearn.naive_bayes import MultinomialNB

In [58]:
nbm = MultinomialNB()

In [59]:
nbm.fit(X_train_cv, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [60]:
X_test_cv = v.transform(X_test)

In [61]:
from sklearn.metrics import classification_report

In [62]:
y_pred= nbm.predict(X_test_cv)

In [63]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       979
           1       0.96      0.88      0.92       136

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [64]:
emails = ["Hey mohan, can we get together to watch footbal game tomorrow?", "Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!"]

In [65]:
emails_count = v.transform(emails)
nbm.predict(emails_count)

array([0, 1], dtype=int64)

### doing the same with pipeline

In [68]:
from sklearn.pipeline import Pipeline ##CONVENİENT apı FOR THE THİNGS WE DİD MANUALLY, 

In [73]:
clf = Pipeline([ 
    ("vectorizer", CountVectorizer()),
    ("nb", MultinomialNB())
     ])

In [74]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('nb',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [75]:
y_pred= clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       979
           1       0.96      0.88      0.92       136

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.95      1115
weighted avg       0.98      0.98      0.98      1115



## movie sentiment analysis

In [9]:
df = pd.read_csv("C:/Users/Owner/nlp-tutorials/9_bag_of_words/movies_sentiment_data.csv")

In [10]:
df.head()

review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [11]:
df.shape

(19000, 2)

In [12]:
df.head(5)

review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [13]:
my_dict= {"positive":1, "negative":0}

In [15]:
df["Category"] = df["sentiment"].map(my_dict)
df.head()

review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [16]:
df.Category.value_counts()

1    9500
0    9500
Name: Category, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df["review"], df["Category"], test_size = 0.2)

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
from sklearn.pipeline import Pipeline

In [31]:
clf = Pipeline([("vectorizer", CountVectorizer()),
               ("rf",RandomForestClassifier(n_estimators=50))
               ])

In [32]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabula...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                

In [33]:
from sklearn.metrics import classification_report

In [37]:
y_preds = clf.predict(X_test)

In [39]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82      1906
           1       0.82      0.81      0.82      1894

    accuracy                           0.82      3800
   macro avg       0.82      0.82      0.82      3800
weighted avg       0.82      0.82      0.82      3800



In [40]:
review = ["It was horrible man!"]

In [41]:
clf.predict(review)

array([0], dtype=int64)

In [42]:
from sklearn.neighbors import KNeighborsClassifier 

In [45]:
clf = Pipeline([("vectorizer", CountVectorizer()),
                ("knnm", KNeighborsClassifier(n_neighbors=10, metric="euclidean"))              
               
               ])

In [46]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('knnm',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='euclidean', metric_params=None,
                                      n_jobs=None, n_neighbors=10, p=2,
                                      weights='uniform'))],
         verbose=False)

In [48]:
y_preds = clf.predict(X_test)

In [50]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.64      0.63      0.64      1906
           1       0.64      0.65      0.64      1894

    accuracy                           0.64      3800
   macro avg       0.64      0.64      0.64      3800
weighted avg       0.64      0.64      0.64      3800



In [51]:
from sklearn.naive_bayes import MultinomialNB

In [53]:
clf = Pipeline([("vectorizer", CountVectorizer()),
                ("knnm", MultinomialNB())              
               
               ])

In [54]:
clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('knnm',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [59]:
y_preds = clf.predict(X_test)

In [61]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1906
           1       0.87      0.81      0.84      1894

    accuracy                           0.85      3800
   macro avg       0.85      0.85      0.85      3800
weighted avg       0.85      0.85      0.85      3800



### Can you write some observations of why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?

- As Machine learning algorithms does not work on Text data directly, we need to convert them into numeric vector and feed that into models while training.
- In this process, we convert text into a very **high dimensional numeric vector** using the technique of Bag of words.
- Model like K-Nearest Neighbours(KNN) doesn't work well with high dimensional data because with large number of dimensions, it becomes difficult for the algorithm to calculate distance in each dimension. In higher dimensional space, the cost to calculate distance becomes expensive and hence impacts the performance of model.
- The easy calculation of probabilities for the words in corpus(Bag of words) and storing them in contigency table is the major reason for the Multinomial NaiveBayes to be a text classification friendly algorithm.
- As Random Forest uses Bootstrapping(Row and column Sampling) with many decision tree and overcomes the high variance and overfitting of high dimensional data and also uses feature importance of words for better classifing the categories.
- Machine Learning is like trial and error scientific method, where we keep trying all the possible algorithms we have and select the one which give good results and satisfy the requirements like latency, interpretability etc.

Refer these resources to get good idea:
- https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/
- https://analyticsindiamag.com/naive-bayes-why-is-it-favoured-for-text-related-tasks/