In [1]:
import pandas as pd
import numpy as np

In [24]:
opinions = ["Where superiority of numbers is overwhelming, it is admittedly is the most important factor in the outcome of an engagement.",
           "Grand strategy should calculate and develop economic resources and man-power of nations in order to sustain the fighting services.",
            "Beyond geography, money has always been the greatest deciding factor in the structure of force.", 
            "Moral elements are among the most important in war. They constitute the spirit that permeates war, and they establish a close affinity with the will that moves and leads the whole mass of force.",
            "Once war is declared, the highest commander in the field must be left complete freedom to act according to his own judgement.",
            "Force employment, or the doctrine and tactics by which forces are actually used in combat-is centrally important, shaping the role of material factors and often predetermining winners and losers. ",
            "In war, three quarters turns on morale; the balance of manpower counts only for the remaining quarter",
            "Those who masters moral influence, weather, terrain, command, and doctrine will win.",
            "Know the enemy and know yourself; in a hundred battles you will win",
            "Strategy directs armies to the decisive points, influences results of the battles.",
            "Strategy is determinant of victorious, with deciding, time, place, and the force of the engagement.",    
            "Indirect approach creates dislocation and paralysis effects in return creates success."
           
           ]

classes = np.array([1,1,1,2,2,2,3,3,3,4,4,4])

In [25]:
df = pd.DataFrame(list(zip(opinions, classes)), columns = ["opinions", "class"])
df

opinions  class
0   Where superiority of numbers is overwhelming, ...      1
1   Grand strategy should calculate and develop ec...      1
2   Beyond geography, money has always been the gr...      1
3   Moral elements are among the most important in...      2
4   Once war is declared, the highest commander in...      2
5   Force employment, or the doctrine and tactics ...      2
6   In war, three quarters turns on morale; the ba...      3
7   Those who masters moral influence, weather, te...      3
8   Know the enemy and know yourself; in a hundred...      3
9   Strategy directs armies to the decisive points...      4
10  Strategy is determinant of victorious, with de...      4
11  Indirect approach creates dislocation and para...      4

In [27]:
from sklearn.model_selection import train_test_split

In [26]:
X= df["opinions"]
y= df["class"]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.2)

In [35]:
X_train.shape

(9,)

In [36]:
X_test.shape

(3,)

In [37]:
X_train[:3]

7    Those who masters moral influence, weather, te...
9    Strategy directs armies to the decisive points...
2    Beyond geography, money has always been the gr...
Name: opinions, dtype: object

In [38]:
#building bag of words model for text rep

from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()

In [39]:
type(X_train.values)

numpy.ndarray

In [40]:
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<9x101 sparse matrix of type '<class 'numpy.int64'>'
	with 136 stored elements in Compressed Sparse Row format>

In [41]:
# change sparse matrix into numpy array

X_train_np = X_train_cv.toarray()

In [42]:
X_train_cv.shape # 120 unique word

(9, 101)

In [44]:
#v.get_feature_names()

In [46]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [49]:
v.get_feature_names_out()

array(['according', 'act', 'affinity', 'always', 'among', 'and',
       'approach', 'are', 'armies', 'battles', 'be', 'been', 'beyond',
       'calculate', 'close', 'command', 'commander', 'complete',
       'constitute', 'creates', 'deciding', 'decisive', 'declared',
       'determinant', 'develop', 'directs', 'dislocation', 'doctrine',
       'economic', 'effects', 'elements', 'enemy', 'engagement',
       'establish', 'factor', 'field', 'fighting', 'force', 'freedom',
       'geography', 'grand', 'greatest', 'has', 'highest', 'his',
       'hundred', 'important', 'in', 'indirect', 'influence',
       'influences', 'is', 'judgement', 'know', 'leads', 'left', 'man',
       'mass', 'masters', 'money', 'moral', 'most', 'moves', 'must',
       'nations', 'of', 'once', 'order', 'own', 'paralysis', 'permeates',
       'place', 'points', 'power', 'resources', 'results', 'return',
       'services', 'should', 'spirit', 'strategy', 'structure', 'success',
       'sustain', 'terrain', 'that', 

In [50]:
v.vocabulary_

{'those': 88,
 'who': 94,
 'masters': 58,
 'moral': 60,
 'influence': 49,
 'weather': 93,
 'terrain': 84,
 'command': 15,
 'and': 5,
 'doctrine': 27,
 'will': 96,
 'win': 97,
 'strategy': 80,
 'directs': 25,
 'armies': 8,
 'to': 90,
 'the': 86,
 'decisive': 21,
 'points': 72,
 'influences': 50,
 'results': 75,
 'of': 65,
 'battles': 9,
 'beyond': 12,
 'geography': 39,
 'money': 59,
 'has': 42,
 'always': 3,
 'been': 11,
 'greatest': 41,
 'deciding': 20,
 'factor': 34,
 'in': 47,
 'structure': 81,
 'force': 37,
 'indirect': 48,
 'approach': 6,
 'creates': 19,
 'dislocation': 26,
 'paralysis': 69,
 'effects': 29,
 'return': 76,
 'success': 82,
 'once': 66,
 'war': 92,
 'is': 51,
 'declared': 22,
 'highest': 43,
 'commander': 16,
 'field': 35,
 'must': 63,
 'be': 10,
 'left': 55,
 'complete': 17,
 'freedom': 38,
 'act': 1,
 'according': 0,
 'his': 44,
 'own': 68,
 'judgement': 52,
 'grand': 40,
 'should': 78,
 'calculate': 13,
 'develop': 24,
 'economic': 28,
 'resources': 74,
 'man': 56,

In [54]:
X_train_np[0]#first opinion

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [53]:
import numpy as np
np.where(X_train_np[0] !=0)

(array([ 5, 15, 27, 49, 58, 60, 84, 88, 93, 94, 96, 97], dtype=int64),)

In [55]:
X_train[:2]

7    Those who masters moral influence, weather, te...
9    Strategy directs armies to the decisive points...
Name: opinions, dtype: object

In [56]:
X_train[:2][7]

'Those who masters moral influence, weather, terrain, command, and doctrine will win.'

In [57]:
#when you convert this email to vector

In [58]:
X_train_np[0][5]

1

In [60]:
v.get_feature_names_out()[5]

'and'

In [61]:
#building ML model

from sklearn.naive_bayes import MultinomialNB
nbm = MultinomialNB()
nbm.fit(X_train_cv, y_train)
X_test_cv = v.transform(X_test)

from sklearn.metrics import classification_report

y_pred= nbm.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_cla

In [62]:
test_opinion = ["Hey mohan, can we get together to watch footbal game tomorrow?", "Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!"]

In [65]:
op_count = v.transform(test_opinion)
nbm.predict(op_count)

array([4, 3])

In [67]:
#doing the same with pipeline

from sklearn.pipeline import Pipeline

clf = Pipeline([ 
    ("vectorizer", CountVectorizer()),
    ("nb", MultinomialNB())
     ])

In [68]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [69]:
y_pred= clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0

    accuracy                           0.00       3.0
   macro avg       0.00      0.00      0.00       3.0
weighted avg       0.00      0.00      0.00       3.0



C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Owner\anaconda3\Lib\site-packages\sklearn\metrics\_cla